### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for netbox_lifecycle

### ISSUE THREAD

**Issue by uck9** [DanSheps/netbox-lifecycle#2]
### Plugin version

v1.0.0

### NetBox version

v3.6.0

### Python version

3.8

### Steps to Reproduce

Trying to load the plugin but getting error on startup.  Using netbox-docker here.

Added 'importlib-metadata' to a plugin-requirements and have it installing the packages, but still getting this issue.  sure I'm just missing something simple here.

### Expected Behavior

Plugin to load

### Observed Behavior

 Traceback (most recent call last):
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/netbox/settings.py", line 729, in <module>
netbox-docker-netbox-1               |     plugin = importlib.import_module(plugin_name)
netbox-docker-netbox-1               |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-docker-netbox-1               |   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
netbox-docker-netbox-1               |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-docker-netbox-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
netbox-docker-netbox-1               |   File "/plugins/netbox-lifecycle/netbox_lifecycle/__init__.py", line 4, in <module>
netbox-docker-netbox-1               |     metadata = metadata('netbox_lifecycle')
netbox-docker-netbox-1               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-docker-netbox-1               |   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 998, in metadata
netbox-docker-netbox-1               |     return Distribution.from_name(distribution_name).metadata
netbox-docker-netbox-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-docker-netbox-1               |   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
netbox-docker-netbox-1               |     raise PackageNotFoundError(name)
netbox-docker-netbox-1               | importlib.metadata.PackageNotFoundError: No package metadata was found for netbox_lifecycle

**Comment by DanSheps** [comment]
Something is not installed properly in your docker instance, I suggest trying to reinstall
