### ISSUE TITLE
Server Error on name sort

### ISSUE THREAD

**Issue by FabryUr** [DanSheps/netbox-lifecycle#47]
### Plugin version

v1.1.3

### NetBox version

v4.1.1

### Python version

3.9

### Steps to Reproduce

1. Click on the "Name" column to sort the data.
2. Refresh the page.
NOTE:
If the error doesn't occur delete the sorting that you have in the url. Also if you want to solve it, in the url insert the following:
"/plugins/lifecycle/lifecycle/?sort=end_of_support"

### Expected Behavior

Firstly it should not throw an error. Also it would be nice to sort the data with the name column. 
In addition it doesn't work for the "hardware" and "assigned object count" fields, so it would be nice to sort by those too.

### Observed Behavior

A Server Error occured, and you cannot make it disappear with reload. The only solution is to modify the url as mentioned before.
![kép_2024-10-03_103844113](https://github.com/user-attachments/assets/db7764fe-dfe1-4257-b7fc-0161be0d8b93)

**Comment by DanSheps** [comment]
To clarify, these are GenericForeignKeys and are not  orderable.  I could likely introduce a specific view for "DeviceType Lifecycle" and "ModuleType Lifecycle" that would be orderable but unfortunately these fields are not.
