### ISSUE TITLE
Reflect all contractual and lifecycle data on all respective objects

### ISSUE THREAD

**Issue by artiomello** [DanSheps/netbox-lifecycle#49]
### Plugin version

v1.1.3

### NetBox version

v4.1.2

### Feature type

New functionality

### Proposed functionality

This plugin needs to reflect all its contractual and lifecycle data on all respective objects.

E.g. a specific device page should display, if defined:
- Hardware lifecycle info
- Assigned licenses
- Applicable contracts
- Applicable EO dates 
- Vendors (maybe)

### Use case

It's required for this plugin to make sense being in Netbox. 

Otherwise, especially considering the current state of development (tables missing any useful info, having non-interactable plaintext objects, broken relationships, etc):
<img width="587" alt="image" src="https://github.com/user-attachments/assets/117574be-32e5-4bd0-b880-f1d4be5ca3f8">
<img width="563" alt="image" src="https://github.com/user-attachments/assets/8bf4a17e-540d-452f-ba75-5c931a5a360c">

A link to a coherent Excel table would be more useful. 

With that said, I really see it being an indispensable plugin in Netbox, uniting all contractual and licensing info under a single product.

**Comment by DanSheps** [comment]
> This plugin needs to reflect all its contractual and lifecycle data on all respective objects.
>
> E.g. a specific device page should display, if defined:
>
> * Hardware lifecycle info
> * Assigned licenses
> * Applicable contracts
> * Applicable EO dates
> * Vendors (maybe)

This isn't a feature request for one specific feature.  I am not going to action this.

> A link to a coherent Excel table would be more useful.

Then go use an Excel table.  This isn't made for you, it is made for myself and released to the public.  I will enterain good faith attempts to engage and will address those as I can but I will not tolerate with this sort of attitude for something:

* that I have released free
* from someone who's first and second issues were combative.

**Comment by artiomello** [comment]
Well, I'm sorry to have offended your feelings. Like I said, I really see this a worthy addition to Netbox, and kudos to you for making this effort.

Sure, I can go ahead and list every item as a separate feature request, explaining the reasoning behind each one. I guess I was trying to point out all that needs to be addressed for your plugin to provide the most benefit without spending a whole day on it. Current tables and their relationships make ir rather confusing to use, thus the excel example.
